# Generated by Django 3.2.6 on 2021-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('desc', models.CharField(max_length=10000000000000)),
            ],
            options={
                'db_table': 'Event',
            },
        ),
    ]
