# Generated by Django 3.2.6 on 2021-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210901_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
