# Generated by Django 3.2.6 on 2021-09-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_event_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CS', 'CS'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('INSTRU', 'INSTRU')], max_length=100)),
                ('time', models.DateTimeField()),
                ('desc', models.CharField(max_length=10000000000000)),
            ],
            options={
                'db_table': 'CSEvent',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='picture',
        ),
    ]
